services:
  backend:
    networks:
      - public
      - private
    environment:
      MONGO_USER: ${MONGO_ROOT_USERNAME:?error}
      MONGO_PASSWORD: ${MONGO_ROOT_PASSWORD:?error}
      MONGO_HOST: mongo
    image: ghcr.io/jonasmetzger2000/mensa-match-backend:main
  frontend:
    networks:
      - public
    ports:
      - 80:80
    image: ghcr.io/jonasmetzger2000/mensa-match-frontend:main
  mongo:
    networks:
      - private
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:?error}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?error}
networks:
  public:
  private: