services:
  backend:
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: se2local
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - public
      - private
  frontend:
    ports:
      - 8080:80
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - public
  mongo:
    image: mongo
    restart: always
    networks:
      - private
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: se2local
  mongo-express:
    image: mongo-express
    networks:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: local
      ME_CONFIG_MONGODB_ADMINPASSWORD: se2local
      ME_CONFIG_MONGODB_URL: mongodb://local:se2local@mongo:27017/
      ME_CONFIG_BASICAUTH: false
networks:
  public:
  private:
  mongo: