rest.openmensa.base.url: https://cvzi.github.io
spring.data.mongodb.host: ${MONGO_HOST:localhost}
spring.data.mongodb.port: ${MONGO_PORT:27017}
spring.data.mongodb.database: ${MONGO_DB:admin}
spring.data.mongodb.username: ${MONGO_USER:root}
spring.data.mongodb.password: ${MONGO_PASSWORD:example}
server.contextPath: /api
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter=DEBUG: