name: Build Frontend Image
permissions: write-all

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'backend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jonasmetzger2000/mensa-match-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}